PREFIX=/usr/local/pushd
BINDIR=$(PREFIX)/bin
LIBDIR=$(PREFIX)/lib
INCDIR=$(PREFIX)/include
CONFDIR=$(PREFIX)/conf
MESSAGEDIR=$(PREFIX)/var/spool
MODULEDIR=$(PREFIX)/libexec

SUPPORT_INCDIR=$(PREFIX)/include
SUPPORT_LIBDIR=$(PREFIX)/lib

#######################################

APPVERSION=1
APPNAME=delayed_pushd

CFLAGS+=-DAPPVERSION=\"$(APPVERSION)\" -DAPPNAME=\"$(APPNAME)\" -DPREFIX=\"$(PREFIX)\" -DDEFAULT_CONFPATH=\"$(CONFDIR)\" -DMESSAGEDIR=\"$(MESSAGEDIR)\" -DDEFAULT_MODULEDIR=\"$(MODULEDIR)\"

